<?php

// The first term here is the name that will appear in the drop-down list
// This has the form $langname['file_name without .php extension'] = "Display Name";
// Try to name your file as the two-letter language code so RompR can pick a suitable
// default language automatically.

$langname['fr'] = "Français";

$languages['fr'] = array (

	// The Sources Chooser Button tooltips
	"button_local_music" => "Musique",
	"button_file_browser" => "Parcourir",
	"button_internet_radio" => "Radios internet",
	"button_albumart" => "Gestion des pochettes",

	// Tooltips for Buttons across the top of the information panel
	"button_togglesources" => "Parcours des sources",
	"button_back" => "Retour",
	"button_history" => "Historique",
	"button_forward" => "Suivant",
	"button_toggleplaylist" => "Parcours des playlists",

	// Tooltips for playlist buttons
	"button_alarm" => "Réveil",
	"button_prefs" => "Préférences",
	"button_clearplaylist" => "Vider les playlist",
	"button_loadplaylist" => "Charger les playlist",
	"button_saveplaylist" => "Sauver les playlist",

	// Tooltips for playback controls
	"button_previous" => "Précédent",
	"button_play" => "Play/Pause",
	"button_stop" => "Stop",
	"button_stopafter" => "Stop à la fin du morceau",
	"button_next" => "Suivant",
	"button_love" => "J'aime",
	"button_ban" => "Bannir",
	"button_volume" => "Régler le volume",
	"button_closewindow" => "Fermer la fenêtre",

	// Configuration menu entries
	"config_language" => "LANGAGE",
	"config_theme" => "THEME",
	"config_hidealbumlist" => "Masquer la liste musicale locale",
	"config_hidefileslist" => "Masquer la liste de fichiers",
	"config_hidelastfm" => "Masquer les stations Last.FM",
	"config_hidepodcasts" => "Masquer les podcasts",
	"config_hideplaylistslist" => "Masquer les playlists sauvegardées",
	"config_hidepluginplaylistslist" => "Masquer les radio personnalisées",
	"config_hidebrowser" => "Masquer le panneau d'informations",
	"config_hideradio" => "Masquer les stations de radio",
	"config_fullbio" => "Récupérer les biographies complètes depuis Last.FM",
	"config_lastfmlang" => "Langues pour Last.FM et Wikipedia",
	"config_lastfmdefault" => "Langue par défaut (English)",
	"config_lastfminterface" => "Langue de l'interface RompR",
	"config_lastfmbrowser" => "Langue par défaut du navigateur",
	"config_lastfmlanguser" => "Cette langue spécifique:",
	"config_langinfo" => "Last.FM et Wikipedia utiliseront l'anglais si il n'y a pas l'information dans votre langue",
	"config_autoscroll" => "Auto-Scroll de la playlist jusqu'à la piste courante",
	"config_autocovers" => "Télécharger automatiquement les pochettes",
	"config_musicfolders" => "Pour utiliser les pochettes de vos dossiers de musique, indiquer les chemins des dossiers ici :",
	"config_crossfade" => "Durée du fondu (secondes)",
	"config_clicklabel" => "Propriété Du Clic De Sélection De Musique",
	"config_doubleclick" => "Double-clic pour ajout, click pour sélection",
	"config_singleclick" => "Click pour ajout, pas de sélection",
	"config_sortbydate" => "Classement des albums par date",
	"config_notvabydate" => "Pas de classement par date pour 'Artistes variés'",
	"config_updateonstart" => "Mise à jour de la musique locale au démarrage",
	"config_updatenow" => "Mise à jour de la musique locale",
	"config_rescan" => "Scan complet de la musique locale",
	"config_editshortcuts" => "Edition des raccourcis clavier...",
	"config_audiooutputs" => "Sorties audio",
	"config_lastfmusername" => "Utilisateur Last.FM",
	"config_loginbutton" => "Connexion",
	"config_scrobbling" => "Scrobbling Last.FM Activé",
	"config_scrobblepercent" => "Pourcentage de pistes à jouer avec Scrobbler",
	"config_autocorrect" => "Auto-correction Last.FM Activée",
	"config_tagloved" => "Tagguer les pistes aimées avec :",
	"config_country" => "PAYS (pour Last.FM)",
	"config_fontsize" => "TAILLE POLICE",
	"config_fontname" => "STYLE POLICE",
	"config_alarm_on" => "Réveil activé",
	"config_showartistbanners" => "Montrer les bannières d'artiste",

	// Various buttons for the playlist dropdowns
	"button_imsure" => "Je suis sûr",
	"button_save" => "Sauver",

	// General Labels and buttons in the main layout
	"label_lastfm" => "Last.FM",
	"button_searchmusic" => "Recherche de musique",
	"button_searchfiles" => "Recherche de fichier",
	"label_yourradio" => "Vos stations de radio",
	"label_podcasts" => "Podcasts",
	"label_somafm" => "Soma FM",
	"label_bbcradio" => "Live BBC Radio",
	"label_icecast" => "Icecast Radio",
	"label_emptyinfo" => "Panneau d'information concernant la musique en cours de lecture",
	"button_playlistcontrols" => "Contrôle de la playlist",
	"button_random" => "ALÉATOIRE",
	"button_crossfade" => "FONDU",
	"button_repeat" => "RÉPÉTITION",
	"button_consume" => "CONSOMMER",
	"label_yes" => "Oui",
	"label_no" => "Non",
	"label_updating" => "Mise à jour des fichiers locaux",
	"label_update_error" => "Echec de la génération de la liste de musique locale !",
	"label_notsupported" => "Opération non supportée !",
	"label_playlisterror" => "Quelque chose s'est mal passé dans la récupération de la liste de lecture !",
	"label_downloading" => "Téléchargement ...",
	"button_OK" => "OK",
	"button_cancel" => "Annuler",
	"error_playlistname" => "Le nom de la liste de lecture comprend des '/'",
	"label_savedpl" => "Liste de lecture sauvée comme %s",
	"label_loadingstations" => "Chargement des stations...",

	// Search Forms
	"label_searchfor" => "Rechercher ...",
	"label_searching" => "Recherche en cours...",
	"button_search" => "Recherche",
	"label_searchresults" => "Résultats",
	"label_multiterms" => "Plusieurs termes peuvent être utilisés simultanément",
	"label_limitsearch" => "Limite des recherches",

	// General multipurpose labels
	"label_tracks" => "pistes",
	"label_albums" => "albums",
	"label_artists" => "artistes",
	"label_track" => "Piste",
	"label_album" => "Album",
	"label_artist" => "Artiste",
	"label_anything" => "Tout",
	"label_genre" => "Genre",
	"label_composer" => "Compositeur",
	"label_performer" => "Interprète",
	"label_rating" => "Note",
	"label_tag" => "Étiquette",
	"label_discogs" => "Discogs",
	"label_musicbrainz" => "Musicbrainz",
	"label_wikipedia" => "Wikipedia",
	"label_general_error" => "Il y a eu une erreur. Merci de rafraîchir cette page et d'essayer à nouveau",
	"label_days" => "jours",
	"label_hours" => "heures",
	"label_minutes" => "minutes",
	"label_noalbums" => "Aucun album trouvé",
	"label_notracks" => "Aucune piste trouvée",
	"label_duration" => "Durée",
	"label_playererror" => "Erreur du lecteur",
	"label_tunefailed" => "Échec de lecture de la station de radio",
	"label_noneighbours" => "Aucun voisin trouvé",
	"label_nofreinds" => "Vous avez 0 amis",
	"label_notags" => "Aucun tag trouvé",
	"label_noartists" => "Aucun artiste trouvé",
	"mopidy_tooold" => "Votre version de Mopidy est trop vieille. Merci de mettre à jour vers la version %s ou supérieure",
	"button_playradio" => "Lecture",

	// Playlist and Now Playing
	"label_waitingforstation" => "Attente des informations de cette station...",
	"label_notforradio" => "Non supporté pour les flux radio",
	"label_incoming" => "Entrant...",
	"label_addingtracks" => "Ajouter des pistes",
	// Now Playing - [track name] by [artist] on [album]
	"label_by" => "par",
	"label_on" => "dans",
	// Now playing - 1:45 of 6:50
	"label_of" => "de",

	// Podcasts
	"podcast_rss_error" => "Échec de traitement du flux RSS",
	"podcast_remove_error" => "Échec de suppression du podcast",
	"podcast_general_error" => "Échec de l’opération :(",
	"podcast_entrybox" => "Entrez l'URL d'un podcast flux RSS feed ici, ou déposez ici son icône",
	// Podcast tooltips
	"podcast_delete" => "Supprimer ce Podcast",
	"podcast_configure" => "Configurer ce Podcast",
	"podcast_refresh" => "Rafraîchir ce Podcast",
	"podcast_download_all" => "Télécharger tous les épisodes de ce Podcast",
	"podcast_mark_all" => "Marquer tous les épisodes comme écoutés",
	"podcast_undelete" => "Restaurer les épisodes supprimés",
	"podcast_removedownloaded" => "Supprimer les fichiers téléchargés",
	// Podcast display options
	"podcast_display" => "Afficher",
	"podcast_display_all" => "Tout",
	"podcast_display_onlynew" => "Nouveaux seulement",
	"podcast_display_unlistened" => "Nouveaux et non écoutes",
	"podcast_display_downloadnew" => "Nouveaux et téléchargés",
	"podcast_display_downloaded" => "Seulement les téléchargements",
	// Podcast refresh options
	"podcast_refresh" => "Rafraîchir",
	"podcast_refresh_never" => "Manuellement",
	"podcast_refresh_hourly" => "Toutes les heures",
	"podcast_refresh_daily" => "Tous les jours",
	"podcast_refresh_weekly" => "Toutes les semaines",
	"podcast_refresh_monthly" => "Tous les mois",
	// Podcast auto expire
	"podcast_expire" => "Conserver les Épisodes Pendant",
	"podcast_expire_tooltip" => "Tout épisode plus ancien que cette durée sera supprimé de la liste. Les changements de cette option prendront effet au prochain rafraîchissement du podcast",
	"podcast_expire_never" => "Toujours",
	"podcast_expire_week" => "Une semaine",
	"podcast_expire_2week" => "Deux semaines",
	"podcast_expire_month" => "Un mois",
	"podcast_expire_2month" => "Deux mois",
	"podcast_expire_6month" => "Six mois",
	"podcast_expire_year" => "Uné année",
	// Podcast number to keep
	"podcast_keep" => "Nombre De Podcasts A Conserver",
	"podcast_keep_tooltip" => "La liste ne montrera que ce nombre d'épisodes. Les changements de cette option prendront effet au prochain rafraîchissement du podcast",
	"podcast_keep_0" => "Pas de limitation",
	// Podcast other options
	"podcast_keep_downloaded" => "Conserver tous les épisodes téléchargés",
	"podcast_kd_tooltip" => "Activer cette option pour conserver tous les épisodes téléchargés. Les deux options précédentes ne s'appliqueront qu'aux épisodes déjà téléchargés",
	"podcast_auto_download" => "Téléchargement automatique des nouveaux épisodes",
	"podcast_tooltip_new" => "Ceci est un nouvel épisode",
	"podcast_tooltip_notnew" => "Cet épisode n'est pas nouveau, mais il n'a pas été écouté",
	"podcast_tooltip_downloaded" => "Cet épisode a été téléchargé",
	"podcast_tooltip_download" => "Télécharger cet épisode sur votre ordinateur",
	"podcast_tooltip_mark" => "Marquer comme écouté",
	"podcast_tooltip_delepisode" => "Supprimer cet épisode",
	"podcast_expired" => "Cet épisode a expiré",
	// eg 2 days left to listen
	"podcast_timeleft" => "%s jours restants pour écouter",

	// Soma FM Chooser Panel
	"label_soma" => "Soma.FM est une radio musicale, non commerciale, diffusée depuis San Francisco exclusivement via internet",
	"label_soma_beg" => "Donations à Soma.FM bienvenues, si vous aimez ces stations",

	// Your radio stations
	"label_radioinput" => "Entrez l'URL d'une station internet ici, ou déposez son bouton Play ici",

	//Album Art Manager
	"albumart_title" => "Pochettes de disques",
	"albumart_getmissing" => "Trouver les pochettes manquantes",
	"albumart_showall" => "Montrer toutes les pochettes",
	"albumart_instructions" => "Sélectionner une pochette pour la changer, ou déplacer une image de votre disque dur ou d'une autre fenêtre du navigateur",
	"albumart_onlyempty" => "Montrer uniquement les albums sans pochette",
	"albumart_allartists" => "Tous les artistes",
	"albumart_unused" => "Images non utilisées",
	"albumart_deleting" => "Suppression ...",
	"albumart_error" => "Ca n'a pas fonctionné",
	"albumart_googlesearch" => "Recherche Google",
	"albumart_local" => "Images locales",
	"albumart_upload" => "Envoi de fichier",
	"albumart_uploadbutton" => "Envoi",
	"albumart_newtab" => "Recherche Google dans un nouvel onglet",
	"albumart_dragdrop" => "Vous pouvez glisser-déposer des images depuis votre disque dur ou depuis une autre fenêtre du navigateur directement par dessus l'image (dans la plupart des navigateurs)",
	"albumart_showmore" => "Montrer plus de résultats",
	"albumart_googleproblem" => "Google dit qu'il y a eu un problème",
	"albumart_getthese" => "Récupérer ces pochettes",
	"albumart_deletethese" => "Supprimer ces pochettes",
	"albumart_nocollection" => "Veuillez créer votre bibliothèque musicale avant d'essayer de télécharger des pochettes",
	"albumart_nocovercount" => "albums sans pochette",
	"albumart_getting" => "Récupération",

	// Setup page (rompr/?setup)
	"setup_connectfail" => "Rompr n'a pas réussi à se connecter à un serveur mpd ou mopidy",
	"setup_connecterror" => "Il y a eu un problème de communication avec votre serveur mpd ou mopidy : ",
	"setup_request" => "Vous avez demandé la page de configuration",
	"setup_labeladdresses" => "Veuillez entrer l'adresse IP et le port de votre serveur mpd dans ce formulaire",
	"setup_addressnote" => "Note: localhost dans ce contexte signifie que votre ordinateur fait tourner un serveur apache",
	"setup_ipaddress" => "Adresse IP ou nom d'hôte",
	"setup_port" => "Port",
	"setup_advanced" => "Options avancées",
	"setup_leaveblank" => "Laissez-les vides à moins que vous n'en ayez l'utilité",
	"setup_password" => "Mot de passe",
	"setup_unixsocket" => "socket UNIX",

	// Intro Window
	"intro_title" => "Informations concernant cette version",
	"intro_welcome" => "Bienvenue dans RompR version",
	"intro_viewingmobile" => "Vous voyez la version mobile de RompR. Pour voir la version standard, allez à",
	"intro_viewmobile" => "Pour voir la version mobile, allez à",
	"intro_basicmanual" => "Le manuel de base de RompR est là :",
	"intro_forum" => "Le Forum de discussion est là :",
	"intro_mopidy" => "IMPORTANT : informations pour les utilisateurs de Mopidy",
	"intro_mopidywiki" => "Si vous utilisez Mopidy, merci de lire le Wiki",
	"intro_mopidyversion" => "Vous devez utiliser Mopidy %s ou postérieur",

	// Last.FM
	"lastfm_loginwindow" => "Connexion à Last.FM",
	"lastfm_login1" => "Cliquez le bouton ci-dessous pour ouvrir le site Last.FM dans un nouvel onglet. Entrez votre identifiant Last.FM si nécessaire et donnez la permission d'accès à RompR",
	"lastfm_login2" => "Vous pouvez fermer le nouvel onglet une fois terminé, mais ne fermez pas cette fenêtre !",
	"lastfm_loginbutton" => "Cliquez ici pour vous connecter",
	"lastfm_login3" => "Une fois connecté sur Last.FM, cliquer sur le bouton OK ci-dessous pour terminer le processus",
	"lastfm_loginfailed" => "Échec de connexion à Last.FM",
	"label_loved" => "J'aime",
	"label_lovefailed" => "Échec de marquage J'aime",
	"label_unloved" => "Je n'aime plus",
	"label_unlovefailed" => "Échec de suppresion du J'aime",
	"label_banned" => "Banni",
	"label_banfailed" => "Échec du banissement",
	"label_scrobbled" => "Scrobblé",
	"label_scrobblefailed" => "Échec de scrobble",

	// Info Panel
	"info_gettinginfo" => "Récupération des infos...",
	"info_newtab" => "Voir dans un nouvel onglet",

	// File Info panel
	"button_fileinfo" => "Informations (Ficher)",
	"info_file" => "Fichier :",
	"info_from_beets" => "(des serveurs beets)",
	"info_format" => "Format :",
	"info_bitrate" => "Debit :",
	"info_samplerate" => "Échantillonnage :",
	"info_mono" => "Mono",
	"info_stereo" => "Stéreo",
	"info_channels" => "Canaux",
	"info_date" => "Date :",
	"info_genre" => "Genre :",
	"info_performers" => "Interprète :",
	"info_composers" => "Compositeurs :",
	"info_comment" => "Commentaire :",
	"info_label" => "Label :",
	"info_disctitle" => "Titre Du Disque :",
	"info_encoder" => "Encodeur :",
	"info_year" => "Année :",

	// Last.FM Info Panel
	"button_infolastfm" => "Informations (Last.FM)",
	"label_notrackinfo" => "Pas d'information trouvée sur cette piste",
	"label_noalbuminfo" => "Pas d'information trouvée sur cet album",
	"label_noartistinfo" => "Pas d'information trouvée sur cet artiste",
	"lastfm_listeners" => "Auditeurs :",
	"lastfm_plays" => "Lectures :",
	"lastfm_yourplays" => "Vos Lectures :",
	"lastfm_toptags" => "TOP TAGS :",
	"lastfm_addtags" => "AJOUT DE TAGS",
	"lastfm_addtagslabel" => "Ajout de tags, séparés par des virgules",
	"button_add" => "AJOUT",
	"lastfm_yourtags" => "VOS TAGS :",
	"lastfm_simar" => "Artistes proches",
	"lastfm_removetag" => "Supprimer le Tag",
	"lastfm_releasedate" => "Date de sortie",
	"lastfm_viewtrack" => "Voir la pise sur Last.FM",
	"lastfm_tagerror" => "Echec de modification des tags",
	"lastfm_loved" => "Aimé",
	"lastfm_lovethis" => "J'aime cette piste",
	"lastfm_unlove" => "Je n'aime plus cette piste",
	"lastfm_notfound" => "%s non trouvé",

	// Lyrics info panel
	"button_lyrics" => "Informations (Paroles)",
	"lyrics_lyrics" => "Paroles",
	"lyrics_nonefound" => "Pas de paroles trouvées",
	"lyrics_info" => "Pour utiliser le visualiseur de paroles, vous devez utiliser Mopidy avec un serveur Beets et vous assurer que vos fichiers sont taggués avec des paroles",
	"lyrics_nopath" => "Pour utiliser la visionneuse de paroles, vous devez vous assurer que vos fichiers locaux sont taggés avec les paroles et définir le chemin de la musique dans les préférences.",

	// For Discogs/Musicbrainz release tables. LABEL in this context means record label
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"title_year" => "ANNEE",
	"title_title" => "TITRE",
	"title_type" => "TYPE",
	"title_label" => "LABEL",
	"label_pages" => "PAGES",

	// For discogs/musicbrains album info. discogs_companies means the companies involved in producing the album
	// These are all section headers and so should all be UPPER CASE, unless there's a good linguistic
	// reason not to do that
	"discogs_companies" => "ENTREPRISES",
	"discogs_personnel" => "PERSONNEL",
	"discogs_videos" => "VIDEOS",
	"discogs_styles" => "STYLES",
	"discogs_genres" => "GENRES",
	"discogs_tracklisting" => "LISTE DES PISTES",
	"discogs_realname" => "NOM RÉEL :",
	"discogs_aliases" => "ALIAS :",
	"discogs_alsoknown" => "AUSSI CONNU COMME :",
	"discogs_external" => "LIENS EXTERNES",
	"discogs_bandmembers" => "MEMBRES DU GROUPE",
	"discogs_memberof" => "MEMBRE DE",
	"discogs_discography" => "DISCOGRAPHIE DE %s",

	// Discogs info panel
	"button_discogs" => "Informations (Discogs)",
	"discogs_error" => "Il y a eu une erreur réseau ou Discogs a refusé de répondre",
	"discogs_nonsense" => "Aucune information pertinente de Discogs",
	"discogs_noalbum" => "Album non trouvé sur Discogs",
	"discogs_notrack" => "Piste non trouvée sur Discogs",

	// Musicbrainz info panel
	"button_musicbrainz" => "Informations (Musicbrainz)",
	"musicbrainz_error" => "Pas de réponse de MusicBrainz",
	"musicbrainz_contacterror" => "Il y a eu une erreur de communication avec Musicbrainz",
	"musicbrainz_noartist" => "Artiste non trouvé sur Musicbrainz",
	"musicbrainz_noalbum" => "Album non trouvé sur Musicbrainz",
	"musicbrainz_notrack" => "Piste non trouvée sur Musicbrainz",
	"musicbrainz_noinfo" => "Pas d'information trouvée sur Musicbrainz",
	// This is used for date ranges -  eg 2005 - Present
	"musicbrainz_now" => "Aujourd'hui",
	"musicbrainz_origin" => "ORIGINE",
	"musicbrainz_active" => "ACTIF",
	"musicbrainz_rating" => "NOTATION",
	"musicbrainz_notes" => "NOTES",
	"musicbrainz_tags" => "TAGS",
	"musicbrainz_externaldiscography" => "Discographie (%s)",
	"musicbrainz_officalhomepage" => "Page officielle (%s)",
	"musicbrainz_fansite" => "Site de fans (%s)",
	"musicbrainz_lyrics" => "Paroles (%s)",
	"musicbrainz_social" => "Réseau social",
	"musicbrainz_microblog" => "Microblog",
	"musicbrainz_review" => "Critiques (%s)",
	"musicbrainz_novotes" => "(Aucun vote)",
	// eg: 3/5 from 15 votes
	"musicbrainz_votes" => "%s/5 sur %s votes",
	"musicbrainz_appears" => "CETTE PISTE APPARAÎT SUR",
	"musicbrainz_credits" => "CREDITS",
	"musicbrainz_status" => "STATUS",
	"musicbrainz_date" => "DATE",
	"musicbrainz_country" => "PAYS",
	"musicbrainz_disc" => "DISQUE",

	// SoundCloud info panel
	"button_soundcloud" => "Informations (SoundCloud)",
	"soundcloud_trackinfo" => "Informations Sur La Piste",
	"soundcloud_plays" => "Lectures",
	"soundcloud_downloads" => "Téléchargements",
	"soundcloud_faves" => "Favoris",
	// State means eg State: Finished or State: Unfinished
	"soundcloud_state" => "Etat",
	"soundcloud_license" => "License",
	"soundcloud_buy" => "Acheter la piste",
	"soundcloud_view" => "Voir sur SoundCloud",
	"soundcloud_user" => "Utilisateur SoundCloud",
	"soundcloud_fullname" => "Nom complet",
	"soundcloud_Country" => "Pays",
	"soundcloud_city" => "Ville",
	"soundcloud_website" => "Visiter le site web",
	"soundcloud_not" => "Ce panneau ne montre que les informations sur la musique venant de SoundCloud",

	// Wikipedia Info Panel
	"button_wikipedia" => "Informations (Wikipedia)",
	"wiki_nothing" => "Rien n'a été trouvé sur Wikipedia",
	"wiki_fail" => "Wikipedia n'a rien pu trouver sur '%s'",
	"wiki_suggest" => "Wikipedia n'a trouvé aucune page correspondant à '%s'",
	"wiki_suggest2" => "Voici quelques suggestions qui ont été indiquées",

	// Keybindings editor
	"title_keybindings" => "Raccourcis clavier",
	"button_volup" => "Monter le volume",
	"button_voldown" => "Baisser le volume",

	// Extras for mobile version
	"button_playlist" => "Playlist",
	"button_playman" => "Gestion de la playlist",
	"button_mob_history" => "Historique du panneau d'information",
	"label_streamradio" => "Radios nationales et locales",
	
	// Various Plugins, Rating, and Tagging
	"stars" => "étoiles",
	"star" => "étoile",
	"label_tags" => "Tags",
	"label_oneresult" => "Résultats de recherche",
	"label_progress" => "Progression",
	"label_wishlist" => "Liste de souhaits",
	"label_viewwishlist" => "Voir votre liste de souhaits",
	"label_addtow" => "Ajouté à la liste de souhaits",
	"label_finished" => "Terminé",
	"config_tagrat" => "Notes et Tags",
	"config_synctags" => "Synchroniser vos tags avec Last.FM",
	"config_loveis" => "Last.FM Love Means",
	"playlist_xstar" => "%s étoiles ou plus",
	"playlist_5star" => "Pistes 5 étoiles ",
	"button_about" => "A propos de RompЯ",
	"label_notfound" => "Track non trouvé",
	// Eg + 3 more
	"label_moreresults" => "%s de +",
	"label_tagmanagertop" => "Drag and Drop depuis la collection de musique ou la playlist pour ajouter des tags aux pistes",
	"label_ratingmanagertop" => "Drag and Drop depuis la collection de musique ou la playlist pour ajouter des evaluations aux pistes",
	"button_createtag" => "CRÉER TAG",

	//New in 0.52
	"config_alarm_ramp" => "Fondu",
	"label_retrieve" => "Récupérer",

	// New in 0.60
	"spotify_error" => "Pas de réponse de Spotify",
	"spotify_noinfo" => "Impossible d'obtenir des informations de Spotify",
	"button_infospotify" => "Informations (Spotify)",
	"config_icontheme" => "ICONES",
	"label_radio" => "Radio",
	"label_pop" => "Popularité",
	"label_albumsby" => "Albums de cet artiste",
	"label_singleartistradio" => "Pistes par artistes",
	"label_mostplayed" => "Pistes favorites",
	"label_neverplayed" => "Pistes jamais jouées",
	"label_radio_fartist" => "Artistes favoris",
	"label_pluginplaylists" => "Radio personalisée",
	"label_recentlyadded_random" => "Pistes récemment ajoutées (aléatoire)",
	"label_recentlyadded_byalbum" => "Albums récemmentajoutés",
	"setup_mpd" => "Réglages MPD/Mopidy",
	"settings_appearance" => "Apparence",
	"settings_panels" => "Panneaux",
	"settings_language" => "Langage",
	"settings_interface" => "Interface",
	"label_charts" => "Top 40",
	"label_choosedomains" => "Rechercher ces sources :",
	"label_dragtoprio" => "(Dragger pour changer la priorité)",
	"button_subscribe" => "Souscrire",
	"config_sortbycomposer" => "Utiliser le compositeur comme tri d'artiste",
	"config_composergenre" => " ... seulement si le genre est :",
	"config_displaycomposer" => "Afficher le compositeur/interprète dans Now Playing",
	"label_radio_mix" => "Artistes préférés et artistes apparentés",
	"label_gotnotracks" => "Je n'ai trouvé aucun track",
	"config_artistfirst" => "Artistes au sommet de la collection",
	"config_nosortprefixes" => "Ignorer ces préfixes lors du tri des artistes",
	"config_sortcollectionby" => "Afficher la collection comme :",
	"config_sortoptions" => "Options de tri de la collection",
	"button_skipforward" => "Suivant",
	"button_skipbackward" => "Précédent",
	"button_alarmsnooze" => "Sonnerie",
	"config_snoozetime" => "Temps de sonnerie (Mins)",
	"config_ramptime" => "Temps de fondu (Secs)",
	"button_rateone" => "Note 1 étoile",
	"button_ratetwo" => "Note 2 étoiles",
	"button_ratethree" => "Note 3 étoiles",
	"button_ratefour" => "Note 4 étoiles",
	"button_ratefive" => "Note 5 étoiles",
	"button_updatecollection" => "Mettre à jour la collection de musique",
	"label_favealbums" => "Albums favoris",
	"button_nextsource" => "Panneau d'informations - Cycle Source",
	"button_now_playing" => "Lecture en cours",
	"button_infopanel" => "Panneau d'informations",
	"config_coversize" => "TAILLE POCHETTE",
	"podcast_sortmode" => "Ordre de tri",
	"podcast_newestfirst" => "Nouveaux en premier",
	"podcast_oldestfirst" => "Anciens en premier",
	"podcast_hidedescriptions" => "Masquer les descriptions",

	// New in 0.64/0.65/0.70
	"label_metabackup" => "Sauvegarde des métadonnées",
	"button_backup" => "Créer une sauvegarde",
	"button_restore" => "Restorer une sauvegarde",
	"button_collectioncontrols" => "Commandes de tri des collections de musique",
	"label_playlistmanager" => "Gestionnaire de playlist",
	"label_playlistmanagertop" => "Drag and Drop de la collection de musique pour ajouter des pistes aux listes de lecture",
	"button_createplaylist" => "CRÉER UNE PLAYLIST",
	"label_renameplaylist" => "Renommer la playlist",
	"button_plugins" => "Plein de bonnes choses",
	"label_filename" => "Nom de fichier",
	"label_resultscollection" => "Collection",
	"label_resultstree" => "Arborescence des répertoires",
	"label_displayresultsas" => "Afficher les resultats comme :",
	"label_files" => "Fichiers",
	"label_allartist" => "Tous les albums ",
	"button_findexact" => "Trouver une correspondance exacte",
	"label_albumartist" => "Artiste de l'album",
	"config_collectionfolders" => "Construire une collection depuis :",
	"button_videos" => "Vidéos connexes",
	"google_error" => "Impossible de contacter Google",
	"label_allrandom" => "Lecture aléatoire",
	"config_background" => "IMAGE DE FOND",
	"lastfm_error" => "Impossible de trouver des informations sur Last.FM",
	"config_skin" => "SKIN",

	// New in 0.71
	"label_albumsbyartist" => "Albums (par Artistes)",
	"config_wheelspeed" => "Vitesse de défilement de la molette de la souris ",
	"label_searchcollectiononly" => "Rechercher uniquement dans la collection de musique",

	"label_lastfm_mix" => "Last FM Lucky Dip",
	"label_lastfm_track" => "Last.FM Mix Radio",
	"label_lastfm_choose" => "Recommandations de base Last.FM sur votre écoute :",
	"label_radio_recommend" => "Recommendations basées sur %s",
	"label_amendalbum" => "Modifier les détails de l'album",

	//CHANGED in 0.60
	"config_country" => "PAYS (pour Last.FM et Spotify)",
	"setup_labeladdresses" => "Si vous rencontrez des problèmes de connexion, essayez d’utiliser une adresse IP au lieu de 'localhost'",
	"setup_ipaddress" => "Serveur Mopidy ou mpd",

	"config_cdplayermode" => "Mode Lecteur CD (ne pas mettre les pistes en attente, démarrer l'album à partir de la piste sélectionnée)",

	"label_recentlyplayed" => "Pistes jouées récemment",
	"label_simar_radio" => "Artistes similaires à",

	"label_tradsearch_header" => "Tapez tout ce que vous cherchez",
	"label_tradsearch" => "Utiliser la recherche traditionnelle avec plusieurs termes",

	"played_never" => "Cette piste n'a jamais été jouée",
	"played_once" => "Cette piste a été jouée une fois",
	"played_twice" => "Cette piste a été jouée deux fois",
	"played_n" => "Cette piste a été jouée %s fois",
	"played_last" => "Joué sur %s",
	"added_on" => "Ajouté à la collection sur %s",
	"button_infoyou" => "Le Discoverator",
	"discover_albums" => "Albums suggérés",
	"discover_now" => "Suggestions de pistes basées sur %s",
	"config_discovembobulate" => "Ouvrir le Discoverator au démarrage",
	"label_spotify_mix" => "Spotify Weekly Mix",
	"label_spotify_dj" => "Spotify Swim",
	"label_spottery_lottery" => "Spotify Surprise!",
	"label_dailymix" => "Votre Mix du jour",
	"label_luckydip" => "Votre coup de chance",
	"label_startshere" => "Votre découverte commence ici",
	"label_getspotify" => "Obtenez Spotify pour commencer à découvrir",
	"because_liked" => "Vous aimez %s, vous pourriez donc aimer :",
	"because_listened" => "Similaire à %s :",
	"albumart_findsmall" => "Trouver des petites images",
	"label_smartsetup" => "En préparation. Patientez s'il-vous-plait....",
	"button_sleep" => "Minuterie d'arrêt",
	"button_filter" => "Filtre",
	"label_tuneinradio" => "Répertoire TuneIn Radio",
	"label_generalsettings" => "Réglages généraux",
	"config_beetsserver" => "Emplacement du serveur Beets (ip.address:port)",
	"config_players" => 'Lecteurs',
	"button_edit_players" => 'Modifier les lecteurs',

	"label_play_all" => "Tout jouer",
	"label_play_options" => "Options de lecture",
	"label_last_played" => "Dernié joué :",
	"label_station_website" => "Site web Station",

	"label_play_whole_album" => "Jouer tout l'album",
	"label_from_collection" => "Lire uniquement les pistes de la collection",
	"label_with_ratings" => "Lire uniquement les pistes notées",
	"label_with_tags" => "Lire uniquement les pistes avec des tags",
	"label_with_tagandrat" => "Lire uniquement les pistes avec des tags et des notations",
	"label_with_tagorrat" => "Lire uniquement les pistes avec des tags ou des notations",
	"config_google_credentials" => "API Google d'informations d'identification ",
	"config_read_the_docs" => "Veuillez lire la documentation",
	"label_dateadded" => "Date ajoutée",
	"label_radiostation" => "Station de radio ",
	"label_opmlimporter" => "Importateur OPML",
	"config_playerintitlebar" => "Afficher le nom du lecteur dans la barre de titre",
	"label_communityradio" => "Navigateur de radio communautaire",
	"label_volume" => "Volume",
	"config_playlistswipe" => "Faites glisser pour supprimer les pistes de la liste de lecture actuelle",
	"button_debuginfo" => "Informations de débogage",
	"config_podcast_defaults" => "Options par défaut pour les nouveaux podcasts",
	"config_marknewasunlistened" => "Marquer les nouveaux épisodes comme non écoutés avant d'actualiser",
	"config_albumartinplaylist" => "Afficher les illustrations de l'album dans la liste de lecture actuelle",
	"label_resume" => "Reprendre",
	"label_sortby" => "Trier par",
	"label_then" => "Ensuite",
	"label_publisher" => 'Éditeur',
	"label_category" => "Categorie",
	"label_new_episodes" => "Nouveaux épisodes",
	"label_unlistened_episodes" => "Épisodes non écoutés",
	"label_loading" => "Chargement ...",
	"label_choosefile" => "Choisir un fichier",
	"label_choosefiles" => "Choisir fichier(s)",
	"label_changevery" => "Changer chaque",
	"label_albumstolistento" => "Albums à écouter",
	"no_albumtolistento" => "Vous pouvez ajouter n’importe quel album Spotify à cette liste à partir du panneau d’information, puis revenir et le consulter à votre guise.",
	"label_addedtolistenlater" => "Ajouté aux albums à écouter",
	"label_all_time" => "Collection entière",
	"label_today" => "Ajouté aujourd'hui",
	"label_thisweek" => "Ajouté cette semaine",
	"label_thismonth" => "Ajouté ce mois-ci",
	"label_thisyear" => "Ajouté cette année",
	"label_deleteplaylist" => "Supprimer cette playlist",
	"label_searchtrack" => "Rechercher cette piste",
	"label_removefromwl" => "Supprimer la piste de la liste de souhaits",
	"label_clickrat" => "Cliquez pour définir le classement",
	"label_clicktag" => "Cliquez pour ajouter des Tags",
	"label_gethelp" => "Cliquez pour l'aide",
	"label_podcastcontrols" => "Commandes de recherche et de tri de podcast",
	"label_closepanel" => "Fermer ce panneau",
	"label_hidepanel" => "Cacher ce panneau",
	"label_removefromplaylist" => "Supprimer de la playlist",
	"label_addtolistenlater" => "Ajouter aux albums à écouter",
	"label_removefromlistenlater" => "Supprimer des albums à écouter",
	"label_addtocollection" => "Ajouter un album à la collection de musique",
	"label_addtoradio" => "Ajouter à vos stations de radio",
	"button_logout" => "Déconnexion",
	"label_transferplaylist" => "Transférer la liste de lecture vers un nouveau lecteur ?",
	"label_yes" => "Oui",
	"label_no" => "Non",
	"podcast_refresh_all" => "Rafraîchir tous les Podcasts",
	"label_global_controls" => "Contrôles globaux",
	"label_topleft" => "En haut à gauche",
	"label_topright" => "En haut à droite",
	"label_bottomleft" => "En bas à gauche",
	"label_bottomright" => "En bas à droite",
	"label_centre" => "Centré",
	"config_preferlocal" => "Préférer la musique locale aux sources Internet",
	"config_lastfm_playcounts" => "Utiliser les comptes Last.FM"

);

?>
